<?php

namespace App\Support;

class FichaCampos
{
    /**
     * Estructura de secciones -> [etiqueta => campo] usada para pintar
     * la ficha completa (por ahora, en el PDF de descarga).
     */
    public static function secciones(): array
    {
        return [
            'Datos generales' => [
                'Denominación' => 'denominacion',
                '¿Forma parte de un polideportivo?' => 'es_polideportivo',
                'Nombre del polideportivo' => 'nombre_polideportivo',
                'Tipo de infraestructura' => 'tipo',
                'Sector' => 'sector',
                'Dirección' => 'direccion',
                'Referencia de dirección' => 'referencia',
                'Google Maps' => 'googlemap',
                'Año de inauguración' => 'anio_inauguracion',
                'Año de último mantenimiento / remodelación' => 'anio_mantenimiento',
            ],
            'Datos administrativos' => [
                'Modalidad de administración' => 'modalidad',
                '¿Cuenta con comité deportivo vecinal?' => 'tiene_comite',
                'N° resolución del comité vecinal' => 'res_comite',
                'Vigencia del comité' => 'vigencia_comite',
                'Presidente — Apellidos y nombres' => 'pres_nombre',
                'Presidente — DNI' => 'pres_dni',
                'Presidente — Celular' => 'pres_cel',
                'Presidente — Dirección' => 'pres_dir',
                'Secretario — Apellidos y nombres' => 'secretario_nombre',
                'Secretario — DNI' => 'secretario_dni',
                'Secretario — Celular' => 'secretario_cel',
                'Fiscalizador — Apellidos y nombres' => 'fiscalizador_nombre',
                'Fiscalizador — DNI' => 'fiscalizador_dni',
                'Fiscalizador — Celular' => 'fiscalizador_cel',
                '¿Entregó copia de ordenanza / reglamentación?' => 'entrega_ordenanza',
                'Existe copia de las llaves en la SGDRJ' => 'copia_llaves_sgdrj',
                'Usa Formulario Único de Autorización' => 'usa_formulario_unico',
                'Tiene Plan de Trabajo Anual (PTA)' => 'tiene_pta',
                'Último informe económico de ingresos' => 'ultimo_informe_economico',
                'Costo de alquiler día (S/)' => 'costo_alquiler_dia',
                'Costo de alquiler noche (S/)' => 'costo_alquiler_noche',
            ],
            'Uso de espacio' => [
                '¿Cuenta con letrero de denominación?' => 'letrero',
                'Condiciones del letrero' => 'letrero_cond',
                '¿Cuenta con letrero de horarios de uso?' => 'letrero_horarios',
                '¿Cuenta con letrero de reglas de uso?' => 'letrero_reglas',
                '¿Cuenta con almacén?' => 'almacen',
                '¿Cuenta con perímetro?' => 'perimetro',
                'Material del perímetro' => 'perimetro_mat',
                'SS.HH. Damas' => 'sshh_damas',
                'SS.HH. Varones' => 'sshh_varones',
                '¿Cuenta con duchas?' => 'duchas',
                '¿Cuenta con gimnasio?' => 'gimnasio',
                '¿Techado del espacio de competencia?' => 'techo_comp',
                'Material del techo (competencia)' => 'techo_comp_mat',
                'Estado del techo (competencia)' => 'techo_comp_estado',
                'Observaciones del techo (competencia)' => 'techo_comp_obs',
                '¿Techado de tribuna?' => 'techo_trib',
                'Material del techo (tribuna)' => 'techo_trib_mat',
                'Estado del techo (tribuna)' => 'techo_trib_estado',
                'Observaciones del techo (tribuna)' => 'techo_trib_obs',
                '¿Cuenta con escenario?' => 'escenario',
                'Escaleras de acceso al escenario' => 'escenario_escaleras',
                '¿Escenario tiene techo?' => 'escenario_techo',
                '¿Parque colindante?' => 'parque',
                'Nombre del parque' => 'parque_nombre',
                '¿Cuenta con kioskos?' => 'kioskos',
                'Kioskos disponibles (#)' => 'kioskos_cantidad',
                '¿Cuenta con parqueo?' => 'parqueo',
                'Capacidad de parqueo (# vehículos)' => 'parqueo_cantidad',
                '¿Cuenta con ambientes multiusos y salones?' => 'ambientes_multiuso',
                'Cantidad de ambientes multiusos' => 'ambientes_multiuso_cantidad',
            ],
            'Ficha técnica deportiva' => [
                'Ancho — específico de juego (m)' => 'med_ancho_juego',
                'Largo — específico de juego (m)' => 'med_largo_juego',
                'Ancho — general (m)' => 'med_ancho_gen',
                'Largo — general (m)' => 'med_largo_gen',
                '¿Cuenta con arcos?' => 'arcos',
                'Material de los arcos' => 'arcos_mat',
                'Ancho del arco (m)' => 'arcos_ancho',
                'Alto del arco (m)' => 'arcos_alto',
                '¿Arcos con mallas?' => 'arcos_mallas',
                '¿Cuenta con arcos móviles?' => 'arcos_moviles',
                'Cantidad de arcos móviles (#)' => 'arcos_moviles_cantidad',
                '¿Cuenta con palcos?' => 'palcos',
                'Número de asientos en palco' => 'palcos_asientos',
                'Número de tribunas (#)' => 'num_tribunas',
                'Capacidad de aforo' => 'aforo',
                'Observaciones de tribunas' => 'tribunas_obs',
                'Vestuarios damas' => 'vest_damas',
                'Vestuarios caballeros' => 'vest_caballeros',
                'Vestuarios con baños' => 'vest_banos',
                'Vestuarios con duchas' => 'vest_duchas',
                '¿Malla perimétrica del espacio de competencia?' => 'malla_perim',
                'Material del espacio de competencia' => 'mat_competencia',
                '¿Tiene medidas oficiales?' => 'medidas_oficiales',
                '¿Cuenta con casilleros / guardarropa?' => 'casilleros',
                '¿Cuenta con andariveles?' => 'andariveles',
                '¿Pisos seguros?' => 'pisos_seguros',
            ],
            'Servicios básicos' => [
                'Servicio de agua' => 'agua',
                'Código de suministro (agua)' => 'agua_cod',
                'Suministro de agua independiente' => 'agua_independiente',
                'Administración ya paga servicio de agua' => 'agua_pagado',
                'Servicio de luz' => 'luz',
                'Código de suministro (luz)' => 'luz_cod',
                'Suministro de luz independiente' => 'luz_independiente',
                'Administración ya paga servicio de luz' => 'luz_pagado',
                'Iluminación general de la infraestructura' => 'ilum_general',
                '¿Cuenta con llave diferencial?' => 'llave_dif',
                '¿Cuenta con llaves térmicas?' => 'llaves_term',
                'Iluminación del campo deportivo' => 'ilum_campo',
                'Tipo de iluminación' => 'ilum_tipo',
                'Número de postes (#)' => 'postes',
                'Estado de iluminación' => 'ilum_estado',
                '¿Tomacorrientes para eventos?' => 'tomacorrientes',
                '¿Sistema de videovigilancia?' => 'videovigilancia',
            ],
            'Defensa civil' => [
                '¿Cuenta con plan de contingencia?' => 'plan_conting',
                '¿Cuenta con espacio para tópico?' => 'topico',
                'Estado del tópico' => 'topico_estado',
                '¿Cuenta con extintor?' => 'extintor',
                'Señalización de seguridad' => 'senal_seguridad',
                'Señalización de salidas' => 'senal_salidas',
                'Señalización de baños' => 'senal_banos',
            ],
        ];
    }
}
